.\" -*- nroff -*-
.TH GEN-WMMOUNTRC 1 "October 1999" "Debian Project" "Debian GNU/Linux"
.SH NAME
gen-wmmountrc \- build a wmmountrc file out of /etc/fstab
.SH SYNOPSIS
\fBgen-wmmountrc > \fIwmmountrc-file\fB\fP
.SH DESCRIPTION
\fBgen-wmmountrc\fP reads \fI/etc/fstab\fP and outputs a file that
can be read by \fBwmmount(1x)\fP
.SH AUTHORS
\fBgen-wmmountrc\fP (first called update-wmmountrc) was written by
\fIMarcelo Magallon <mmagallo@debian.org>\fP based on a similar program
distributed with wmmount by \fISam Hawker <shakie@geocities.com>\fP.
.sp
This manual page was written by \fIMarcelo Magallon
<mmagallo@debian.org>\fP
.SH COPYRIGHT
\fBgen-wmmountrc\fP and this manual page are GNU Copyright 1998 Marcelo
Magallon \fI<mmagallo@debian.org>\fP.
.SH "SEE ALSO"
.BR wmmount (1x),
.BR fstab (5).
