.\" -*- nroff -*-
.TH GEN-WMMOUNTRC 1 "January 2000" "Debian Project" "Debian GNU/Linux"
.SH NAME
gen-wmmountrc \- build a wmmountrc file out of /etc/fstab
.SH SYNOPSIS
.B gen-wmmountrc
[> \fIwmmountrc-file\fP]
.SH DESCRIPTION
.B gen-wmmountrc
reads /etc/fstab file and outputs a file that can be read by
.BR wmmount (1x).
Usual location of wmmountrc file is /etc/system.wmmount.
.SH AUTHORS
.B gen-wmmountrc
(first called update-wmmountrc) was written by Marcelo Magallon
<mmagallo@debian.org>, based on a similar program distributed with
wmmount, by Sam Hawker <shawkie@geocities.com>.
.sp
This manual page was written by Marcelo Magallon, and, along with
the program, later updated by Josip Rodin.
.SH "SEE ALSO"
.BR wmmount (1x),
.BR fstab (5).
